sudo: true

language: bash

env:
  CODECOV_TOKEN="d2c2565c-d5a0-4b62-b1e0-dfcb734fe9f8"

before_install:
  - dcutil_program_installation_dir=/tmp/local/bin
  - mkdir -p $dcutil_program_installation_dir
  - export PATH=$PATH:$dcutil_program_installation_dir
  - dcutil_dir="$(dirname $(pwd))"
  - dcutil_libs="${dcutil_dir}/dcutil-libs"
  - mkdir -p ${dcutil_libs}/{docker-compose,makefiles}
  - touch ${dcutil_libs}/.env
  - mv ${dcutil_dir}/dcutil ${dcutil_program_installation_dir}/.dcutil
  - cd ${dcutil_program_installation_dir}/.dcutil
  - ./install.sh $dcutil_program_installation_dir ${dcutil_libs}
  - source ~/.bashrc && source ~/.bash_profile

script:
  - ./libs/bats/bin/bats test

branches:
  only:
    - /.*/

notifications:
  email:
    on_success: never
    
