sudo: true

language: bash

before_install:
  - dcutil_program_installation_dir=/tmp/local/bin
  - mkdir -p $dcutil_program_installation_dir
  - export PATH=$PATH:$dcutil_program_installation_dir
  - dcutil_dir="$(dirname $(pwd))"
  - cp -R "${dcutil_dir}/dcutil/dcutil-libs-example" "${dcutil_dir}/dcutil-libs"
  - cp "${dcutil_dir}/dcutil/.env.example" "${dcutil_dir}/dcutil-libs/.env"
  - dcutil_libs="${dcutil_dir}/dcutil-libs"
  - mv ${dcutil_dir}/dcutil ${dcutil_program_installation_dir}/.dcutil
  - ./install.sh $dcutil_program_installation_dir $dcutil_dir $dcutil_libs
  - source ~/.bashrc && source ~/.bash_profile

script:
  - ./libs/bats/bin/bats test

branches:
  only:
    - /.*/

notifications:
  email:
    on_success: never
    
